import type { ApiEnvelope, User } from "./types";
const KEYS=["auth_token","refresh_token","auth_user","token_expires_at"] as const,LOCK="sub2api-auth-token-refresh";let inFlight:Promise<string>|null=null,localTokenRotation=0;
export class ApiRequestError extends Error{constructor(message:string,public status:number){super(message)}}
export class AuthSessionChangedError extends Error{constructor(){super("SESSION_CHANGED");this.name="AuthSessionChangedError"}}
export const clearSession=()=>KEYS.forEach(k=>localStorage.removeItem(k));
const userId=()=>{try{return Number(JSON.parse(localStorage.getItem("auth_user")||"null")?.id)||null}catch{return null}};
export const sessionSnapshot=()=>`${localStorage.getItem("auth_token")??""}\0${localStorage.getItem("refresh_token")??""}`;
async function refreshInner(){const refreshToken=localStorage.getItem("refresh_token");if(!refreshToken)throw new Error("NO_REFRESH_TOKEN");const snapshot={refreshToken,user:userId()};const adopt=()=>{const access=localStorage.getItem("auth_token"),next=localStorage.getItem("refresh_token"),expires=Number(localStorage.getItem("token_expires_at"));return access&&next&&next!==snapshot.refreshToken&&userId()===snapshot.user&&expires>Date.now()?access:null};const run=async()=>{const peer=adopt();if(peer)return peer;const response=await fetch("/api/v1/auth/refresh",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({refresh_token:snapshot.refreshToken})});if(!response.ok){await new Promise(r=>setTimeout(r,1000));const won=adopt();if(won)return won;throw new Error("REFRESH_REJECTED")}const payload=(await response.json()) as ApiEnvelope<{access_token:string;refresh_token:string;expires_in:number}>;if(payload.code!==0||!payload.data)throw new Error(payload.message||"REFRESH_FAILED");if(localStorage.getItem("refresh_token")!==snapshot.refreshToken||userId()!==snapshot.user){const won=adopt();if(won)return won;throw new AuthSessionChangedError()}localStorage.setItem("auth_token",payload.data.access_token);localStorage.setItem("token_expires_at",String(Date.now()+payload.data.expires_in*1000));localStorage.setItem("refresh_token",payload.data.refresh_token);localTokenRotation++;return payload.data.access_token};if(navigator.locks)return navigator.locks.request(LOCK,run);return run()}
export function refreshToken(){if(inFlight)return inFlight;const task=refreshInner();inFlight=task;const cleanup=()=>{if(inFlight===task)inFlight=null};void task.then(cleanup,cleanup);return task}
export async function apiFetch<T>(path:string,init:RequestInit={},signal?:AbortSignal):Promise<T>{const token=localStorage.getItem("auth_token"),headers=new Headers(init.headers);headers.set("accept","application/json");if(init.body)headers.set("content-type","application/json");if(token)headers.set("authorization",`Bearer ${token}`);let response=await fetch(`/api/v1${path}`,{...init,headers,signal});if(response.status===401&&token&&localStorage.getItem("refresh_token")){try{const next=await refreshToken();headers.set("authorization",`Bearer ${next}`);response=await fetch(`/api/v1${path}`,{...init,headers,signal})}catch{if(localStorage.getItem("auth_token")===token){clearSession();sessionStorage.setItem("auth_expired","1");window.location.assign(`/login?redirect=${encodeURIComponent(location.pathname+location.search)}`)}throw new Error("会话已过期")}}if(response.status===403)window.dispatchEvent(new Event("insights-auth-revalidate"));if(!response.ok){const message=(await response.json().catch(()=>null))?.message||`请求失败 (${response.status})`;throw new ApiRequestError(readableApiError(message),response.status)}const payload=(await response.json()) as ApiEnvelope<T>|T;if(payload&&typeof payload==="object"&&"code" in payload){const envelope=payload as ApiEnvelope<T>;if(envelope.code!==0)throw new Error(envelope.message||"请求失败");return envelope.data}return payload as T}
export async function verifySession(expected=sessionSnapshot()):Promise<User>{const rotation=localTokenRotation,expectedUser=userId(),data=await apiFetch<User|{user:User}>("/auth/me"),user="user" in data?data.user:data;if(sessionSnapshot()!==expected&&(localTokenRotation===rotation||(expectedUser!==null&&expectedUser!==user.id)))throw new AuthSessionChangedError();localStorage.setItem("auth_user",JSON.stringify(user));return user}
export async function logout(){const refresh=localStorage.getItem("refresh_token");try{if(refresh)await apiFetch("/auth/logout",{method:"POST",body:JSON.stringify({refresh_token:refresh})})}finally{clearSession();window.location.assign("/login")}}


function readableApiError(message: string): string {
 const descriptions:Record<string,string>={
  DETAIL_OUTSIDE_RETENTION:"所选日期超出明细保留范围，仍可查看已保留的汇总数据。",
  AGGREGATE_OUTSIDE_GATEWAY_RETENTION:"所选日期不再保留小时明细，请改用天、周或月粒度。",
 };
 return descriptions[message] || message;
}
