import { afterEach, describe, expect, it, vi } from "vitest";
import { ApiRequestError, AuthSessionChangedError, apiFetch, clearSession, refreshToken, verifySession } from "./auth";
afterEach(()=>{localStorage.clear();vi.restoreAllMocks()});
describe("session isolation",()=>{
 it("clears all shared Sub2API session keys",()=>{for(const k of ["auth_token","refresh_token","auth_user","token_expires_at"])localStorage.setItem(k,"x");clearSession();expect(localStorage.length).toBe(0)});
 it("discards an old auth/me response after the token changes",async()=>{localStorage.setItem("auth_token","A");let resolve!:(value:Response)=>void;vi.spyOn(globalThis,"fetch").mockReturnValue(new Promise(r=>{resolve=r}));const pending=verifySession();localStorage.setItem("auth_token","B");localStorage.setItem("auth_user",JSON.stringify({id:2}));resolve(new Response(JSON.stringify({id:1}),{status:200}));await expect(pending).rejects.toBeInstanceOf(AuthSessionChangedError);expect(JSON.parse(localStorage.getItem("auth_user")||"{}").id).toBe(2)});
 it("accepts its own token refresh while verifying the same account",async()=>{localStorage.setItem("auth_token","expired");localStorage.setItem("refresh_token","refresh-a");localStorage.setItem("auth_user",JSON.stringify({id:7}));vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(new Response("",{status:401})).mockResolvedValueOnce(new Response(JSON.stringify({code:0,data:{access_token:"fresh",refresh_token:"refresh-b",expires_in:3600}}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({id:7,role:"admin"}),{status:200}));await expect(verifySession()).resolves.toMatchObject({id:7});expect(localStorage.getItem("auth_token")).toBe("fresh");expect(JSON.parse(localStorage.getItem("auth_user")||"{}").id).toBe(7)});
 it("requests an authoritative role recheck on 403",async()=>{let events=0;const listener=()=>events++;window.addEventListener("insights-auth-revalidate",listener);vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({message:"forbidden"}),{status:403}));await expect(apiFetch("/admin/insights/departments")).rejects.toBeInstanceOf(ApiRequestError);expect(events).toBe(1);window.removeEventListener("insights-auth-revalidate",listener)});
 it("cleans up a rejected refresh without creating an unhandled derived promise",async()=>{localStorage.setItem("refresh_token","bad");vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("",{status:400}));await expect(refreshToken()).rejects.toThrow("REFRESH_REJECTED");await new Promise(r=>setTimeout(r,0))});
});
