import { afterEach, describe, expect, it, vi } from "vitest";
import { adaptModelProfile, insightsApi } from "./api";
afterEach(()=>{vi.restoreAllMocks();localStorage.clear()});
const meta={timezone:"Asia/Shanghai",generated_at:"2026-09-22T00:00:00Z",coverage:[]};
describe("model API contract",()=>{
 it("adapts complete profile arrays, capabilities and sample counts",()=>{expect(adaptModelProfile({identity:{platform:"openai",name:"gpt/test"},profile:{use_cases:["coding"],reasoning:"supported",tool_calling:"unsupported",structured_output:"unknown",sources:[{label:"docs",url:"https://example.test",updated_at:"2026-01-01"}],version:7},performance:{ttft_samples:8,tpot_samples:9}})).toMatchObject({id:"openai:gpt/test",useCases:["coding"],reasoning:"supported",toolCalling:"unsupported",version:7,metrics:{ttft:{sampleCount:8},tpot:{sampleCount:9}}})});
 it("uses encoded detail query and complete profile PUT DTO",async()=>{const profile={identity:{platform:"openai",name:"gpt/test"},profile:{use_cases:[],sources:[],version:2},performance:{}};const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(new Response(JSON.stringify({data:profile,meta}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({version:3}),{status:200}));await insightsApi.model("openai:gpt/test","24h");const model=adaptModelProfile(profile);await insightsApi.saveModel(model.id,{...model,useCases:["code"],inputModalities:["text"],outputModalities:["text"],contextLimit:1,maxOutput:2});expect(String(fetchMock.mock.calls[0][0])).toContain("/insights/models/detail?model=openai%3Agpt%2Ftest&window=24h");expect(String(fetchMock.mock.calls[1][0])).toContain("/admin/insights/models/profile?model=openai%3Agpt%2Ftest");expect(JSON.parse(String((fetchMock.mock.calls[1][1] as RequestInit).body))).toMatchObject({expected_version:2,use_cases:["code"],context_limit:1,input_modalities:["text"]})});
 it("reports a missing shared heatmap scale as a contract error",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({data:{year:2026,days:[{date:"2026-01-01",total_tokens:1,state:"value"}]},meta}),{status:200}));await expect(insightsApi.personalHeatmap(2026)).rejects.toThrow("热力图响应缺少跨年份共享色阶")});
 it("calls compare with repeated model parameters",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({data:{models:[],trends:[]},meta}),{status:200}));await insightsApi.compareModels(["p:a","p:b"],"7d");expect(String(vi.mocked(fetch).mock.calls[0][0])).toContain("model=p%3Aa&model=p%3Ab&window=7d")});
});
